# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

encoding: UTF-8

# Site Settings
title: "MenderCon 2023"
email: "info@mendercon.com"
description: "MenderCon is a conference for people who are passionate about modernizing and improving software systems"
baseurl: ""
url: "https://mendercon.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"
isAcceptingSponsors: false

collections:
  faqs:
    output: true

# Head
metaKeywords: "mendercon, menders, unconference, refactoring, development, programming, legacy, code, software, remodeling, technical, debt"
mastodonServer: "https://toot.legacycode.rocks"
mastodonAccount: "@mendercon"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcMastodon: "/img/seo/sharing-mastodon.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://forms.gle/ve2YcKycdFUxUGZh6"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/coc/", text: "Code of Conduct"}
 - {permalink: "/testimonials/", text: "Testimonials"}
 - {permalink: "http://legacycode.rocks", text: "Community"}
 - {permalink: "/faq/", text: "FAQ"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "MenderCon 2023"
eventDate: "May 10, 2023"
heroButtons:
 - {permalink: "#about", text: "Learn more"}
 - {link: "https://www.eventbrite.com/e/mendercon-2023-tickets-559111556717", text: "Get tickets"}

# About Block
aboutTitle: "About MenderCon"
aboutBlock:
 - {title: "Focused<br/>Content", image: "conference.jpg", text: "A full day focused on modernizing and improving software systems. From the smallest apps, to the biggest enterprise monoliths. Find your people and learn here." }
 - {title: "Virtual Unconference", image: "workshop.jpg", text: "At this conference, the attendees get to create the bulk of the schedule on the fly. And because staring at a screen watching endless presentations from your home isn't a ton of fun, we're going to encourage attendees to create a variety of different session types." }
 - {title: "Find<br/>Your People", image: "hackathon.jpg", text: "You're not alone! There are other people just like you who enjoy working on existing codebases. Meet them here. Make friends. Expand your network." }

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Conference Hall"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "22 Teatral'na St"
eventAddressLocality: "Lviv"
eventAddressLocalityRegion: "Lvivska"
eventPostalCode: "79000"
eventAddressCountry: "Ukraine"
eventStartTime: "2014-10-25T10:00"
eventDoorTime: "09:00"
eventEndTime: "2014-10-25T20:00"
eventPlaceCoordinates: "49.843237, 24.028751"
mapCenterCoordinates: "49.842537, 24.025701"
mapMobileCenterCoordinates: "49.841620, 24.029411"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Toots Feed Block
tootsFeedImage: "mastodon-feed.jpg"
tootsFeedTitle: "What's Up?"
mastodonHashTag: "MenderCon2023"
mastodonFeedUrl: "https://toot.legacycode.rocks/api/v1/timelines/tag/MenderCon2023"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true
